### ISSUE TITLE
Assign Nest to NestNode every time you quote

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#14]
Convenient to upgrade, the NestNode ledger will be re-booked in 3.5

**Comment by inf-loop** [comment]
what's the percentage of NN rewards (NEST tokens), which is 15% in v3.0.  In forthcoming v3.5, the share of 5% for dev-team is removed. we need to confirm the reward percentage. @MLY0813

**Comment by NestProtocol** [comment]
> NN奖励（NEST代币）的百分比是多少，在v3.0中为15％。在即将发布的v3.5中，删除了5％的开发团队份额。我们需要确认奖励百分比。@ MLY0813

NN:15%
Quoter:80%
NEST_DAO:5%
