### ISSUE TITLE
NToken quotation requires 2 quotation interfaces

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#16]
1.Does not include ntoken quotes,It can be called when the total circulation of ntoken is less than 1 million.
2.Including ntoken quotation,It can be called when the total circulation of ntoken is greater than 1 million.

**Comment by inf-loop** [comment]
So it's best if we don't check the limit (1 mil). Any miner decides which quotation interface he will call.

**Comment by MLY0813** [comment]
> 因此，最好不要检查限制（100万）。任何矿工都决定他将呼叫哪个报价接口。

The assets transferred in these two interfaces are different and the risks are different, but the mining is the same. Miners will choose the low risk interface, that is the quote interface without ntoken.
