### ISSUE TITLE
Quotation ETH asset is equal to the base quotation scale

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#17]
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/develop-miningv1/contracts/NestMiningV1.sol#L294

require(ethNum == state.miningEthUnit && ethNum % state.miningEthUnit == 0, "Nest:Mine:!(ethNum)");

Quotation ETH asset is equal to the base quotation scale.

**Comment by inf-loop** [comment]
right
