### ISSUE TITLE
No fee is required for order-taking transactions

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#18]
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/develop-miningv1/contracts/libminingv1/MiningV1Op.sol#L56
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/develop-miningv1/contracts/libminingv1/MiningV1Op.sol#L154

No fee is required for order-taking transactions

**Comment by inf-loop** [comment]
Setting `biteFeeRate` to zero does solve the issue
