### ISSUE TITLE
已拍卖的ntoken向后兼容

### ISSUE THREAD

**Issue by unrelenting-d1x** [NEST-Protocol/NEST-Oracle-V3.5#2]
Even through we plan to remove the auction mechanism

but the contract should still **maintain the rewards sharing arrangement prior to the 3.5 release**

Chat log:

已经拍卖出去的ntoken怎么处理，现在去除 分账，这些ntoken owner 会不会有意见？
还是保持之前的分成，已拍卖的ntoken向后兼容。

**Comment by inf-loop** [comment]
done
