### ISSUE TITLE
Need to return more information to the chain.

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#20]
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/develop-miningv1/contracts/libminingv1/MiningV1Data.sol#L117

PriceSheetPub and PriceSheet have the same structure.

**Comment by inf-loop** [comment]
check `NestMining.fullPriceSheet()`, which is for off-chain, i.e. no contract allowed. While PriceSheetPub is for on-chain sheet retrieving, so it only has limited fields.
