### ISSUE TITLE
The post interface needs to increase the judgment of the total circulation of NToken

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#21]
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/main/contracts/NestMiningV1.sol#L290

The post interface needs to increase the judgment of the total circulation of NToken, and the total circulation of NToken is less than 1 million to call the post method.

**Comment by inf-loop** [comment]
add a constant in MiningV1Data.sol
```js
uint256 constant MINING_NTOKEN_NON_DUAL_POST_THRESHOLD = 1_000_000 ether; 
```
