### ISSUE TITLE
why the sigma square parameter could be negative？

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [NEST-Protocol/NEST-Oracle-V3.5#39]
https://github.com/NEST-Protocol/NEST-Oracle-V3.5/blob/ff3e0e0237436351ccb4b71fb350fab6d1e349a6/contracts/NestMiningV1.sol#L742

**Comment by paradox607** [comment]
The parameter value  of sigma must be non-negative and the absolute value is not essential:
`abs()`
