### ISSUE TITLE
报价手续费、预言机调用费分配

### ISSUE THREAD

**Issue by MLY0813** [NEST-Protocol/NEST-Oracle-V3.5#6]
USDT/NEST/ETH报价对，报价手续费，20%进入NEST_DAO，80%进入NEST收益池。
Token/NToken/ETH报价对，报价手续费，20%进入NToken_DAO，20%进入NEST_DAO。60%进入各个Token收益池。
调用费用（0.01ETH）全部进入各个DAO中。

**Comment by inf-loop** [comment]
Despite the higher gas cost, it was added.
